package Views;

import Models.Videojuegos;
import Models.VideojuegosDAO;
import java.awt.GridLayout;
import java.awt.Image;
import java.sql.SQLException;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 * Clase para mostrar la lista de videojuegos en forma de tarjetas.
 */
public class frmListadoVideojuegos extends javax.swing.JFrame {

    /**
     * Creates new form frmListadoVideojuegos
     */
    public frmListadoVideojuegos() {
        initComponents();
        cargarVideojuegos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Listado de Videojuegos");

        panelVideojuegos = new javax.swing.JPanel();
        panelVideojuegos.setLayout(new GridLayout(0, 2, 10, 10)); // Configurar el layout como dos columnas de tarjetas

        JScrollPane scrollPane = new JScrollPane(panelVideojuegos);
        getContentPane().add(scrollPane);

        pack();
        setLocationRelativeTo(null); // Centrar la ventana en la pantalla
    }// </editor-fold>                        

    private void cargarVideojuegos() {
        try {
            VideojuegosDAO dao = new VideojuegosDAO();
            List<Videojuegos> listaVideojuegos = dao.obtenerTodosLosVideojuegos();

            for (Videojuegos videojuego : listaVideojuegos) {
                JPanel card = new JPanel();
                card.setLayout(new GridLayout(0, 1));
                card.setPreferredSize(new java.awt.Dimension(250, 300));
                
                JLabel lblTitulo = new JLabel("Título: " + videojuego.getTitulo());
                JLabel lblPlataforma = new JLabel("Plataforma: " + videojuego.getPlataforma());
                JLabel lblGenero = new JLabel("Género: " + videojuego.getGenero());
                JLabel lblPrecio = new JLabel("Precio: " + videojuego.getPrecio());
                JLabel lblStock = new JLabel("Stock: " + videojuego.getStock());
                
                JLabel lblImagen = new JLabel();
                if (videojuego.getImagen() != null) {
                    ImageIcon icon = new ImageIcon(videojuego.getImagen());
                    Image img = icon.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH);
                    lblImagen.setIcon(new ImageIcon(img));
                } else {
                    lblImagen.setText("Sin Imagen");
                    lblImagen.setHorizontalAlignment(JLabel.CENTER);
                }
                
                JButton btnModificar = new JButton("Modificar");
                btnModificar.addActionListener(evt -> abrirFormularioModificacion(videojuego));

                card.add(lblImagen);
                card.add(lblTitulo);
                card.add(lblPlataforma);
                card.add(lblGenero);
                card.add(lblPrecio);
                card.add(lblStock);
                card.add(btnModificar);
                
                panelVideojuegos.add(card);
            }

            panelVideojuegos.revalidate();
            panelVideojuegos.repaint();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al cargar los videojuegos");
        }
    }

    private void abrirFormularioModificacion(Videojuegos videojuego) {
        frmControlVideoJuego formulario = new frmControlVideoJuego(videojuego);
        formulario.setVisible(true);
        this.dispose(); // Cierra la ventana actual
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmListadoVideojuegos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmListadoVideojuegos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmListadoVideojuegos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmListadoVideojuegos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmListadoVideojuegos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel panelVideojuegos;
    // End of variables declaration                   
}